name: move
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

  #MOVE PACKAGES
  cached_network_image:
  shared_preferences: ^2.0.6
  http: ^0.12.0+1
  flutter_html: ^2.1.1
  url_launcher:
  shifting_tabbar: ^1.0.2
  flutter_switch: ^0.3.2
  platform_device_id: ^1.0.1
  fluttertoast: ^8.0.8
  encrypt: ^4.0.0
  email_validator: ^1.0.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
